services:
  frontend:
    build:
      context: ./frontend  # ここを ./ にせず、./frontend に固定
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # 物理的なファイルの繋がりを強制する
    volumes:
      - ./frontend:/app
      - /app/node_modules # コンテナ内のライブラリは保護
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - black-lab-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - black-lab-net

networks:
  black-lab-net:
    driver: bridge


